name: 3741-VoDinhBachMai

on:
  push:
    branches:
      - main  # Change this to the branch you're working on
  workflow_dispatch: # This allows manual triggering

jobs:
  run-playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust this to your Node.js version if necessary

      - name: Install dependencies
        run: npm ci

      # **New Step: Install Playwright Browsers**
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --reporter=line,allure-playwright

      - name: Setup Allure environment
        run: |
          npm install -g allure-commandline --save-dev
          mkdir -p allure-results

      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
