name: 3741-VoDinhBachMai

on:
  workflow_dispatch: # Enables the workflow to be run manually from the GitHub Actions tab

jobs:
  run-playwright-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # Specify the Node.js version

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test --reporter=line,allure-playwright

      - name: Setup Allure environment
        run: |
          npm install -g allure-commandline --save-dev
          mkdir -p allure-results # Ensure the allure-results folder exists

      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
